M48
; DRILL file {KiCad 9.0.2} date 2025-06-13T08:34:27-0700
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-06-13T08:34:27-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.2
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.700
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.000
%
G90
G05
T1
X37.3Y-0.7
X37.3Y-2.5
X42.9Y-0.7
X42.9Y-2.5
X52.2Y-0.7
X52.2Y-2.5
T2
X0.0Y-18.0
X58.4Y-18.0
M30
