M48
; DRILL file {KiCad 7.0.2-0} date 2024 March 07, Thursday 21:22:03
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-03-07T21:22:03-08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.2-0
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C4.000
%
G90
G05
T1
X64.128Y-87.503
X64.128Y-126.873
X129.928Y-87.503
X129.928Y-126.873
T0
M30
